### ISSUE TITLE
update papers results without the wei quirk

### ISSUE THREAD

**Issue by timm** [ai-se/activeconfig#20]
we need to show siegmund and sven the corrected numbers after that quirk is removed

**Comment by vivekaxl** [comment]
![cpm_sql1](https://cloud.githubusercontent.com/assets/6147456/9802225/a270052c-57e6-11e5-83b0-cc100b8928f2.png)
![cpm_x2641](https://cloud.githubusercontent.com/assets/6147456/9802221/a26a5168-57e6-11e5-960a-a26b1049b0ca.png)
![cpm_bdbc1](https://cloud.githubusercontent.com/assets/6147456/9802220/a26951aa-57e6-11e5-9078-f06c9df5d2af.png)
![cpm_bdbj1](https://cloud.githubusercontent.com/assets/6147456/9802223/a26deae4-57e6-11e5-8fbe-e36d092509c8.png)
![cpm_llvm1](https://cloud.githubusercontent.com/assets/6147456/9802222/a26c26d2-57e6-11e5-82e7-085283f7a57a.png)
![cpm_apache_training_reduction1](https://cloud.githubusercontent.com/assets/6147456/9802224/a26e1bd6-57e6-11e5-932e-431bc3688d2f.png)

**Comment by timm** [comment]
your y-axis says mre variance. do you mean that or do you mean MRE?

and is our preferred method east-west-where?

also, how does these results compare with the two apel papers that recommended sub-sampling methods (one from fourier series and one from random sub-sampling)

t

**Comment by vivekaxl** [comment]
Done!
