### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/activeconfig#22]
Table 8 shows the distribution of the collected configuration is-
sues across the categories. Remarkably, a significant percentage (17.3%∼48.5%) of issues fit into the “difficulties” category. This indicates users’ tremendous difficulties to find the right knobs from the large configuration space. 

From "Hey, You Have Given Me Too Many Knobs!"

**Comment by timm** [comment]
keep em coming

**Comment by vivekaxl** [comment]
"Since domain of such function is a finite set, with an arbitary function f, knowing f(a) provides practically no information about f(b) unless a=b. That is to say performance values cannot be predicted by merely taking samples of configurations.

From "Performance Prediction of configurable systems by fourier learning"- This can be used to say that the problem is non-trivial

**Comment by vivekaxl** [comment]
can't use the stuff from the fourier leaning stuff since, it says that sampling is not a good way to build a model.

Added the ref of the knobs paper.
