### ISSUE TITLE
Configuration Explosion Problem

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/activeconfig#23]
@article{yilmaz2006covering,
  title={Covering arrays for efficient fault characterization in complex configuration spaces},
  author={Yilmaz, Cemal and Cohen, Myra B and Porter, Adam and others},
  journal={Software Engineering, IEEE Transactions on},
  volume={32},
  number={1},
  pages={20--34},
  year={2006},
  publisher={IEEE}
}

**Comment by timm** [comment]
related work? what sample sizes did they get down to? competitive with GALE? better?

**Comment by vivekaxl** [comment]
Yeah. This can be a reference to configuration explosion problem

**Comment by vivekaxl** [comment]
added to the paper
