### ISSUE TITLE
Need to add the configuration of the machine where the simulations were run

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/activeconfig#26]

**Comment by timm** [comment]
to confirm:
- when you say that east-west where used (say) 10% of the the data
- you mean it clustered 10% then evaluated 2log(N) of that 10%
  - which for 5000 training examples, 2log_2(5000*0.1) < 20

am i right?

so can we get charts showing the number of **evaluatuations** required by the different methods
- the fourier series stuff
- the random sampling stuff (from sven, this year)
- East-West Where?

hopefully, what we will see is EW-where is less than the the others

**Comment by vivekaxl** [comment]
Correct!
Say there are n features so the number of configurations is N = 2^n (assuming all the configurations are valid)
- we plan use 2/3rd of the N and performance 2log_2(2/3 \* N).

We can't do a fair comparison with the other methods because
- random sampling algorithms(Dr. Sven's) is an iterative algorithm while ours is a deterministic algorithm. 
- Fourier attempts to determine the samples required to achieve _any_ desired accuracy which makes it adaptive, progressive sampling. 

I found a table in the fourier paper, which we can use
![screenshot 2015-09-12 09 58 36](https://cloud.githubusercontent.com/assets/6147456/9831844/dc6044dc-5934-11e5-9338-3b619bcc6f88.png)

@timm: Shouldn't I implement all these approaches to make this comparison?

**Comment by timm** [comment]
something. do something,
