### ISSUE TITLE
There is floating point error in the results

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/activeconfig#27]
![screenshot 2015-09-12 19 21 48](https://cloud.githubusercontent.com/assets/6147456/9834338/8aa4e8a6-5983-11e5-9818-627226e45adb.png)
![screenshot 2015-09-12 19 21 27](https://cloud.githubusercontent.com/assets/6147456/9834339/8aa647e6-5983-11e5-9bd5-9207476d5eeb.png)

**Comment by vivekaxl** [comment]
The above code snippets cause floating point errors.

**Comment by timm** [comment]
Say what? no idea
