### ISSUE TITLE
Evaluation Results

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/activeconfig#30]
| Percentage | Random | Baseline | Exemplar | East West | Apache |
| --- | --- | --- | --- | --- | --- |
| 10 | 8 | 20 | 8 | 16 |  |
| 20 | 8 | 39 | 8 | 16 |  |
| 30 | 16 | 58 | 16 | 32 |  |
| 40 | 16 | 77 | 16 | 32 |  |
| 50 | 16 | 96 | 16 | 32 |  |
| 60 | 16 | 116 | 16 | 32 |  |
| 70 | 16 | 135 | 16 | 32 |  |
| 80 | 16 | 154 | 16 | 32 |  |
| 90 | 16 | 173 | 16 | 32 |  |
| Percentage | Random | Baseline | Exemplar | East West | BDBJ |
| 10 | 8 | 18 | 8 | 16 |  |
| 20 | 8 | 36 | 8 | 16 |  |
| 30 | 15 | 55 | 15 | 30 |  |
| 40 | 16 | 72 | 16 | 32 |  |
| 50 | 16 | 90 | 16 | 32 |  |
| 60 | 16 | 108 | 16 | 30 |  |
| 70 | 16 | 126 | 16 | 30 |  |
| 80 | 16 | 145 | 16 | 32 |  |
| 90 | 16 | 163 | 16 | 32 |  |
| Percentage | Random | Baseline | Exemplar | East West | BDBC |
| 10 | 30 | 256 | 30 | 60 |  |
| 20 | 30 | 512 | 30 | 60 |  |
| 30 | 30 | 768 | 30 | 60 |  |
| 40 | 52 | 1024 | 52 | 104.6 |  |
| 50 | 52 | 1280 | 52 | 105.1 |  |
| 60 | 52 | 1536 | 52 | 100.8 |  |
| 70 | 52 | 1792 | 52 | 103.7 |  |
| 80 | 51 | 2049 | 51 | 102.6 |  |
| 90 | 51 | 2305 | 51 | 100.3 |  |
| Percentage | Random | Baseline | Exemplar | East West | SQL |
| 10 | 29.7 | 466 | 29.9 | 59.7 |  |
| 20 | 32.65 | 931 | 32.5 | 65.4 |  |
| 30 | 52.15 | 1396 | 51.6 | 104.1 |  |
| 40 | 52.6 | 1862 | 53.05 | 102.7 |  |
| 50 | 56.35 | 2327 | 50.5 | 101.5 |  |
| 60 | 51.35 | 2796 | 50.95 | 102.6 |  |
| 70 | 49.95 | 3258 | 50.9 | 103.2 |  |
| 80 | 51.2 | 3723 | 51.95 | 100.9 |  |
| 90 | 81.85 | 4188 | 80.6 | 161.4 |  |
| Percentage | Random | Baseline | Exemplar | East West | x264 |
| 10 | 16 | 116 | 16 | 31.7 |  |
| 20 | 22.4 | 231 | 22.6 | 44.5 |  |
| 30 | 29.95 | 346 | 29.85 | 58.5 |  |
| 40 | 30.05 | 461 | 29.8 | 59.4 |  |
| 50 | 30.35 | 576 | 30.3 | 60.5 |  |
| 60 | 20.35 | 692 | 29.2 | 59.9 |  |
| 70 | 29.8 | 807 | 36.25 | 60.4 |  |
| 80 | 29.3 | 922 | 29.45 | 59.1 |  |
| 90 | 51.1 | 1037 | 52 | 108.54 |  |
| Percentage | Random | Baseline | Exemplar | East West | LLVM |
| 10 | 15.6 | 103 | 15.9 | 32 |  |
| 20 | 15.9 | 205 | 15.9 | 31.4 |  |
| 30 | 30.5 | 308 | 29.95 | 60.6 |  |
| 40 | 29.95 | 410 | 30.2 | 59 |  |
| 50 | 29.75 | 512 | 29.75 | 60.4 |  |
| 60 | 29.55 | 615 | 29.65 | 58.7 |  |
| 70 | 29.95 | 717 | 30.05 | 58.2 |  |
| 80 | 30.3 | 820 | 29.6 | 60.1 |  |
| 90 | 29.7 | 922 | 29.35 | 58.5 |  |

**Comment by timm** [comment]
i added a baseline/east west column

![image](https://cloud.githubusercontent.com/assets/29195/9866779/c67c4fba-5b34-11e5-8b32-8e39c77efadf.png)
