### ISSUE TITLE
need tables on mean and sd of more

### ISSUE THREAD

**Issue by timm** [ai-se/activeconfig#36]

**Comment by vivekaxl** [comment]
![screen shot 2015-10-02 at 11 04 20 am](https://cloud.githubusercontent.com/assets/6147456/10249842/64bc6836-68f5-11e5-9e34-1b2a126cdcfe.png)

**Comment by timm** [comment]
so in call cases, when "Measurement (Them)" is less than "Measurement (Us)", we have median and sd error rates

ok. we are still in the game

**Comment by timm** [comment]
Have you got latex for the above table?

What does the green stuff mean?

**Comment by vivekaxl** [comment]
Latex code for the table:

\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{multirow}
\usepackage[table,xcdraw]{xcolor}

\begin{document}

% Please add the following required packages to your document preamble:

% If you use beamer only pass "xcolor=table" option, i.e. \documentclass[xcolor=table]{beamer}
\begin{table}[]
\centering
\caption{My caption}
\label{my-label}
\begin{tabular}{|l|l|l|l|l|l|l|}
\hline
                                               &                                              &                                              & \multicolumn{2}{l|}{\textbf{FaultRate(Them)}}               & \multicolumn{2}{l|}{\textbf{FaultRate(US)}}                                                   \ \cline{4-7} 
\multirow{-2}{_}{\textbf{Program}}             & \multirow{-2}{_}{\textbf{Measurement(Them)}} & \multirow{-2}{_}{\textbf{Measurement(Us)}}   & \textbf{Mean}                & \textbf{Std}                 & \textbf{Mean}                                 & \textbf{Std}                                  \ \hline
                                               & 15                                           &                                              & \cellcolor[HTML]{34FF34}44.1 & \cellcolor[HTML]{34FF34}42.3 &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 139                                          &                                              & 3.9                          & 5.3                          &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 160                                          &                                              & 2.8                          & 3.7                          &                                               &                                               \ \cline{2-2} \cline{4-5}
\multirow{-4}{_}{BDBC}                         & 164                                          & \multirow{-4}{_}{64}                         & 2.8                          & 3.7                          & \multirow{-4}{_}{9.3}                         & \multirow{-4}{_}{6.8}                         \ \hline
                                               & 10                                           &                                              & \cellcolor[HTML]{34FF34}17.7 & \cellcolor[HTML]{34FF34}19.6 &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 48                                           &                                              & \cellcolor[HTML]{34FF34}8.5  & \cellcolor[HTML]{34FF34}9.6  &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 116                                          &                                              & \cellcolor[HTML]{34FF34}3.8  & \cellcolor[HTML]{34FF34}5.7  &                                               &                                               \ \cline{2-2} \cline{4-5}
\multirow{-4}{_}{BDBJ}                         & 162                                          & \multirow{-4}{_}{64}                         & 1.7                          & 3.5                          & \multirow{-4}{_}{2.7}                         & \multirow{-4}{_}{0.7}                         \ \hline
                                               & 9                                            &                                              & \cellcolor[HTML]{34FF34}14.9 & \cellcolor[HTML]{34FF34}24.8 &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 29                                           &                                              & \cellcolor[HTML]{34FF34}7.7  & \cellcolor[HTML]{34FF34}11.2 &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 80                                           &                                              & \cellcolor[HTML]{34FF34}11.6 & \cellcolor[HTML]{34FF34}22.7 &                                               &                                               \ \cline{2-2} \cline{4-5}
\multirow{-4}{_}{Apache}                       & 143                                          & \multirow{-4}{_}{16}                         & 5.3                          & 10.8                         & \multirow{-4}{_}{9.9}                         & \multirow{-4}{_}{2.4}                         \ \hline
\rowcolor[HTML]{34FF34} 
\cellcolor[HTML]{34FF34}                       & 26                                           & \cellcolor[HTML]{34FF34}                     & 7.8                          & 9.2                          & \cellcolor[HTML]{34FF34}                      & \cellcolor[HTML]{34FF34}                      \ \cline{2-2} \cline{4-5}
\rowcolor[HTML]{34FF34} 
\cellcolor[HTML]{34FF34}                       & 566                                          & \cellcolor[HTML]{34FF34}                     & 9.3                          & 12.5                         & \cellcolor[HTML]{34FF34}                      & \cellcolor[HTML]{34FF34}                      \ \cline{2-2} \cline{4-5}
\rowcolor[HTML]{34FF34} 
\cellcolor[HTML]{34FF34}                       & 566                                          & \cellcolor[HTML]{34FF34}                     & 7.1                          & 9.1                          & \cellcolor[HTML]{34FF34}                      & \cellcolor[HTML]{34FF34}                      \ \cline{2-2} \cline{4-5}
\rowcolor[HTML]{34FF34} 
\multirow{-4}{_}{\cellcolor[HTML]{34FF34}SQL}  & 569                                          & \multirow{-4}{_}{\cellcolor[HTML]{34FF34}64} & 7                            & 9                            & \multirow{-4}{_}{\cellcolor[HTML]{34FF34}5.6} & \multirow{-4}{_}{\cellcolor[HTML]{34FF34}0.2} \ \hline
\rowcolor[HTML]{34FF34} 
\cellcolor[HTML]{34FF34}                       & 11                                           & \cellcolor[HTML]{34FF34}                     & 7.8                          & 9                            & \cellcolor[HTML]{34FF34}                      & \cellcolor[HTML]{34FF34}                      \ \cline{2-2} \cline{4-5}
\rowcolor[HTML]{34FF34} 
\cellcolor[HTML]{34FF34}                       & 62                                           & \cellcolor[HTML]{34FF34}                     & 7.4                          & 10.2                         & \cellcolor[HTML]{34FF34}                      & \cellcolor[HTML]{34FF34}                      \ \cline{2-2} \cline{4-5}
\rowcolor[HTML]{34FF34} 
\cellcolor[HTML]{34FF34}                       & 62                                           & \cellcolor[HTML]{34FF34}                     & 7.4                          & 10.2                         & \cellcolor[HTML]{34FF34}                      & \cellcolor[HTML]{34FF34}                      \ \cline{2-2} \cline{4-5}
\rowcolor[HTML]{34FF34} 
\multirow{-4}{_}{\cellcolor[HTML]{34FF34}LLVM} & 88                                           & \multirow{-4}{_}{\cellcolor[HTML]{34FF34}32} & 5.7                          & 7                            & \multirow{-4}{_}{\cellcolor[HTML]{34FF34}3.3} & \multirow{-4}{_}{\cellcolor[HTML]{34FF34}0.3} \ \hline
                                               & 12                                           &                                              & \cellcolor[HTML]{34FF34}29.8 & \cellcolor[HTML]{34FF34}22   &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 81                                           &                                              & \cellcolor[HTML]{34FF34}17.9 & \cellcolor[HTML]{34FF34}27.2 &                                               &                                               \ \cline{2-2} \cline{4-5}
                                               & 89                                           &                                              & 5.1                          & 15.1                         &                                               &                                               \ \cline{2-2} \cline{4-5}
\multirow{-4}{_}{x264}                         & 89                                           & \multirow{-4}{_}{32}                         & 5.1                          & 15.1                         & \multirow{-4}{_}{6.6}                         & \multirow{-4}{*}{0.5}                         \ \hline
\end{tabular}
\end{table}
\end{document}

**Comment by vivekaxl** [comment]
Green color indicates that we are better than the Norbert's recommended method.
