### ISSUE TITLE
vivek

### ISSUE THREAD

**Issue by timm** [ai-se/activeconfig#39]
in the  raw data files for apache bdbc bdbj llvm sql x264 u used for this study, what is the unit of time? minutes?

**Comment by timm** [comment]
@vivekaxl : need an answer

**Comment by vivekaxl** [comment]
Sorry about the delay.

Well the dependent variable is a performance measure and it doesn't have a standard unit.

Apache: The dependent variable is the request rate at which the web server could no longer respond or produced connection errors(It is a number of requests)
BDBC + BDBJ + SQL: It is the time required to execute the benchmark provided by the vendor. (BDBC has fractions, BDBJ has numbers like 3000 and SQL has numbers like ~14)
LLVM: We measure the time LLVM needs to compile its standard test suite. (Seconds..I think)
x264: We measured the time needed to encode the video trailer Sintel (735 MB). (Seconds)

Reference: http://www.infosun.fim.uni-passau.de/cl/publications/docs/ICSE2012.pdf (page 7)
