### ISSUE TITLE
Final Lap

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/activeconfig#45]
- [x] some of your eps figures have bogus white space on top. plz remove them so they are flush to top of page. 
- [x] also, your RQ results standout boxes often loss their top line. please fix 
- [x] also also, some of those boxed were "orphans".. all by themselves on start of next page. please avoid that (e.g. by removing orphan text lines in the proceeding paras

**Comment by timm** [comment]
nice job with the latex placement!
