### ISSUE TITLE
fixes to the paper

### ISSUE THREAD

**Issue by timm** [ai-se/activeconfig#46]
vivek,
@svenapel  has 3 last set of changes
- [x] references need fixing. many lower case that should be upper. ref11 has no journal. etc etc
- [x] all figs need to work in b&w gray scale. especially fig6
- [x] sql should be sqllite all the way thru, including figures

also, anway we can not have \ssubsection 5.4 start with one para that has no connection to the next page?

![image](https://cloud.githubusercontent.com/assets/29195/13409746/52a48286-df02-11e5-8070-9f7e4e61f267.png)

**Comment by vivekaxl** [comment]
Done
