### ISSUE TITLE
planning next steps

### ISSUE THREAD

**Issue by timm** [ai-se/activeconfig#48]
![image](https://cloud.githubusercontent.com/assets/29195/13581290/32840eb4-e474-11e5-9650-e6bb711f5bdc.png)
# Questions:
- [x] so we've seen some of thse before? like x264 llvm and BDBC and BDBJ?
- [x] where's sqllite?
- [x] is there a feature model available for all? (so we know what are illegal mutants)?
- [x] there are only 3 with multi-objectives ?
  - hSMGP: 3
  - TriMashL 3
  - x264: 8
- [x]  should we ignore the small ones with single goal. So ignore Clasp,  Lrzip, Apache, BDB-J?
# To do (Proposed)
-  Implement Vivek's next trick 
         - sort the clusters found by WHAT according to the distances within each cluster, 
         - iteratively sample, in order of the ones with lowest variance on that measure
         - stop sampling when no improvement on a CART model built from 30 labelled instances
                          - this is just a heuristic assessment tree, 
                          - no promises here that such a tree will perform well in an absolute sense
                          - but current experiments show that such a tree can work well in a  relative sense in that in can serve to detect when new samples do not improve score from older samples.
         - experiments with current data show that this approach can sample less than the FSE paper are result in estimates with no worse mean error but much less variance.
- apply the  new trick to  single objective that we have not tried before. note that this might be enough for a journal-level extension to an accepted FSE paper.
           - [ ] Java GC
           -  [ ] AJstats
           -  [ ] HIPA
           - [ ] Dune
           - [ ] and not BDBC, LLVM (done before)
- then we go multi-goal optimization (whole new round of papers)
          - [ ] TriMash-MG
          -  [ ] x264 
          - [ ] HSMGP

**Comment by svenapel** [comment]
-  so we've seen some of thse before? like x264 llvm and BDBC and BDBJ?
  Correct
-  where's sqllite?
  For our latest experiments, we did not use it anymore, but of course, the data set is still there.
-  is there a feature model available for all? (so we know what are illegal mutants)?
  Yes.
-  there are only 3 with multi-objectives ?
  Currently, yes. But recently we bought advanced energy measurment equipment...
-  should we ignore the small ones with single goal. So ignore Clasp, Lrzip, Apache, BDB-J?
  No, these are widely-used real-world systems. I would included them always.

**Comment by timm** [comment]
@vivekaxl 
any comment on the above? a more pragmatic ordering? any halfway steps i missed above?

@svenapel 

> Currently, yes. But recently we bought advanced energy measurement equipment...

very cool. now i'm a little nervous of an 8 goal problem. are then (small) N number of most used energy measures? turn all our problems into N goals?

**Comment by vivekaxl** [comment]
It is correct except for a tiny little detail.

> old: stop sampling when no improvement on a CART model built  from 30 labelled instances</old> 
>  new: stop sampling when no improvement on a CART model tested on labelled instances selected using WHAT (The idea is it is important to get the correct representatives in the small test set)

Ah, says @timm to @vivekaxl . I understand

**Comment by svenapel** [comment]
@timm 

> very cool. now i'm a little nervous of an 8 goal problem. are then (small) N number of most used 
> energy measures? turn all our problems into N goals?

maybe two or three. anyway, we can also include memory consumption and binary footprint. in some cases, we have also application-specific or domain-specific goals/properties, but we will need to work on this.

**Comment by timm** [comment]
@vivekaxl . any thoughts on how you'd handle the n-goals? move from cart to gale?

**Comment by timm** [comment]
@vivekaxl please pull apart this issue and #49 into , er, three or four issues
