### ISSUE TITLE
same questions as before:

### ISSUE THREAD

**Issue by timm** [ai-se/activeconfig#49]
- [ ] is there a feature model available for all? (so we know what are illegal mutants)?
- [ ]  should we ignore the four really small ones with single goal? zipMe Elevator Email prevalorPP

![image](https://cloud.githubusercontent.com/assets/29195/13615381/11f038ec-e543-11e5-938c-196ce56c0482.png)

**Comment by svenapel** [comment]
> is there a feature model available for all? (so we know what are illegal mutants)?

Yes

> should we ignore the four really small ones with single goal? zipMe Elevator Email prevalorPP

Let's ignore Elevator and Emal. The other two are real-world systems.
